fabricamusical:
  outputs:
    dev:
      dataset: dw
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: chave_bq.json
      location: US
      method: service-account
      priority: interactive
      project: fabrica-musical-dw
      threads: 1
      type: bigquery
  target: dev