name: dbt run

on:
  schedule:
    - cron: '0 10-23 * * *'
  workflow_dispatch:

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
      
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core==1.8.8
        pip install dbt-bigquery==1.8.3
        
    - name: Criar arquivo de credenciais
      shell: bash
      run: |
        cd dbt/fabricamusical
        echo "${{ secrets.GOOGLE_CREDENTIALS }}" | base64 --decode > chave_bq.json

    - name: Comandos dbt
      run: |
        cd dbt/fabricamusical
        dbt run --profiles-dir .
